### ISSUE TITLE
ParseDSN fills MaxIdleConns, MaxOpenConns, ConnMaxLifetime leading to `cannot connect. invalid settings.`

### ISSUE THREAD

**Issue by kabachook** [ClickHouse/clickhouse-go#570] opened 2022-05-10 16:15 UTC
### Issue description
`ParseDSN` fills `MaxIdleConns, MaxOpenConns, ConnMaxLifetime` with default values in `Options` struct leading to error after opening a connection:
`cannot connect. invalid settings. use SetMaxIdleConns,SetMaxOpenConns,SetConnMaxLifetime (see https://pkg.go.dev/database/sql)`

Current workaround:
```go
options, err := clickhouse.ParseDSN(...)
options.MaxIdleConns = 0
options.MaxOpenConns = 0
options.ConnMaxLifetime = 0
db = clickhouse.OpenDB(options)
db.SetMaxIdleConns(5)
db.SetMaxOpenConns(10)
db.SetConnMaxLifetime(time.Hour)
``` 

### Example code
```go
options, err := clickhouse.ParseDSN("clickhouse://default:default@testhost.local:9440/db?debug=true&secure=true&skip_verify=true")
if err != nil {
	log.Fatal(err)
}
db = clickhouse.OpenDB(options)
err = db.Ping(ctx.Backgound())
if err != nil {
    log.Fatal(err)
}
```

### Error log
```
cannot connect. invalid settings. use SetMaxIdleConns,SetMaxOpenConns,SetConnMaxLifetime (see https://pkg.go.dev/database/sql)
```

### Configuration
*OS:* macOS 12.2.1

*Interface:*`database/sql`

*Driver version:* `github.com/ClickHouse/clickhouse-go/v2 v2.0.14`

*Go version:* `go version go1.17.8 darwin/amd64`

*ClickHouse Server version:*  `ClickHouse (redacted) server version 22.4.4 revision 54455`

**Comment by rolinh** [comment] 2022-05-11 08:32
The root of the issue is actually about not being consistent when setting defaults. Indeed, `clickhouse.OpenDB()` [mutates](https://github.com/ClickHouse/clickhouse-go/blob/709552525332569d5c212b7de6c0b268075e5fbe/clickhouse_std.go#L86) the options struct passed in parameter to set some defaults. As part of the defaults that are set, there are `MaxIdleConns`, `MaxOpenconns` and `ConnMaxLifetime` as you can see [here](https://github.com/ClickHouse/clickhouse-go/blob/709552525332569d5c212b7de6c0b268075e5fbe/clickhouse_options.go#L153-L161). So calling `OpenDB()` a second time with the same options struct results in a failure.

The code snippet below illustrates the issue:
```go
package main

import (
        "log"

        "github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
        options := &clickhouse.Options{}
        db := clickhouse.OpenDB(options)
        err := db.Ping()
        if err != nil {
                log.Fatal("db ", err)
        }
        db2 := clickhouse.OpenDB(options)
        err = db2.Ping()
        if err != nil {
                log.Fatal("db2 ", err)
        }
}
```
Output:
```
2022/05/11 10:22:49 OH NOES: cannot connect. invalid settings. use SetMaxIdleConns,SetMaxOpenConns,SetConnMaxLifetime (see https://pkg.go.dev/database/sql)
exit status 1
```

Overall, it seems that callers must not set any of `MaxIdleConns`, `MaxOpenconns` and `ConnMaxLifetime` in the options struct but instead call the corresponding setters from `database/sql`. I am thus left to wonder why are these 3 parameters even part of the options struct?

**Comment by gingerwizard** [comment] 2022-05-13 09:11
Looking into a fix for this. So `ParseDSN` itself sets defaults. This is logical to ensure they are set to sensible values. Users can then override these values with the respective methods - which is exactly as intended. 

The challenge arises when opendb then checks these to see if they are not default - [complaining if they are set.](https://github.com/ClickHouse/clickhouse-go/blob/709552525332569d5c212b7de6c0b268075e5fbe/clickhouse_std.go#L71-L85). This sort of makes sense - users are being forced to set them through the connection object to be consistent with the standard [https://pkg.go.dev/database/sql](https://pkg.go.dev/database/sq)l. This isn't compatible with ParseDSN however due to it setting default values. 

I think the solution is simple `ParseDSN` shouldn't set default values and rather this should be done in `Open`.

I need to test all combinations though. Alot of this stems from the reuse of the Options struct across native and std.

**Comment by gingerwizard** [comment] 2022-05-13 09:48
@rolinh @kabachook i believe https://github.com/ClickHouse/clickhouse-go/pull/579 resolves this. Feedback appreciated. thanks to you both for reporting and investigating.

**Closed** 2022-05-13 14:09 UTC
Labels: bug

**Comment by rolinh** [comment] 2022-05-16 13:56
@gingerwizard Thanks for your patch. I'm still a bit lost though: Why are `MaxIdleConns`, `MaxOpenconns` and `ConnMaxLifetime` part of `Options` if users cannot set them to some non-zero value? IMHO, either they shouldn't be part of the `Options` struct or users should be allowed to set them to some value. Also, note that your patch doesn't solve the problem I mentioned above (ie that the `options` struct is being mutated by `OpenDB/Open` and so options can't be reused.

**Comment by gingerwizard** [comment] 2022-05-16 15:25
I believe the intention is to force the user to use the methods consistent with the database/sql specification. The options struct is shared with the native protocol - hence the overlap. I presume this was a code-saving measure but I'm hypothesizing as to the original authors intent.

Re re-use of the `Options` struct, I think this worthy of an issue. I'm hesitant to make this change in a minor release but a refactoring of this is defn more an ideal solution @rolinh
