### ISSUE TITLE
clickhouse-go/v2 v2.3.0 compile error : assertion failed

### ISSUE THREAD

**Issue by Meppo** [ClickHouse/clickhouse-go#782] opened 2022-10-13 03:23 UTC
### Issue description

`compile error`

```bash
# compile os: docker from  golang:1.18
$ go version
go version go1.18.4 linux/amd64

$ go run "/workspaces/clickhouse-err/main.go"
# github.com/ClickHouse/ch-go/proto
/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/col_map.go:124:11: internal compiler error: assertion failed
```

### Example code

- benchmark example code: [benchmark/v2/write-native-struct/main.go](https://github.com/ClickHouse/clickhouse-go/blob/main/benchmark/v2/write-native-struct/main.go)
- `go.mod`

```bash
module mych

go 1.18

require github.com/ClickHouse/clickhouse-go/v2 v2.3.0

require (
	github.com/ClickHouse/ch-go v0.47.3 // indirect
	github.com/andybalholm/brotli v1.0.4 // indirect
	github.com/go-faster/city v1.0.1 // indirect
	github.com/go-faster/errors v0.6.1 // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/klauspost/compress v1.15.9 // indirect
	github.com/paulmach/orb v0.7.1 // indirect
	github.com/pierrec/lz4/v4 v4.1.15 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/segmentio/asm v1.2.0 // indirect
	github.com/shopspring/decimal v1.3.1 // indirect
	go.opentelemetry.io/otel v1.9.0 // indirect
	go.opentelemetry.io/otel/trace v1.9.0 // indirect
	golang.org/x/sys v0.0.0-20220811171246-fbc7d0a398ab // indirect
)

```

**Comment by gingerwizard** [comment] 2022-10-19 10:54
i can't reproduce this...have pushed a small project which reproduces your example @Meppo 
https://github.com/gingerwizard/awesomeProject

@ernado any ideas as this seems to originate from ch-go

**Comment by gingerwizard** [comment] 2022-10-19 11:11
Tested above project on 

go version go1.18.7 darwin/arm64
and
go version go1.19 darwin/arm64

**Comment by ernado** [comment] 2022-10-19 11:17
This is internal compiler error, probably caused by compiler bug.

Just use latest go version: go1.18.7 or go1.19.2.

**Comment by gingerwizard** [comment] 2022-10-19 14:39
Closing as not reproducible. @Meppo reopen if you can reproduce on 1.18.7 or 1.19.2

**Closed by gingerwizard** 2022-10-19 14:39 UTC
Labels: question
