### ISSUE TITLE
INSERT does not work with query parameters with async_insert = 1

### ISSUE THREAD

**Issue by arunk-s** [ClickHouse/clickhouse-go#1356] opened 2024-07-22 13:14 UTC
## Observed

When using named query parameters in insertion query (as shown [here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01015_insert_values_parametrized.sh)) with `AsyncInsert` method, the library fails to find parameters correctly.

## Expected behaviour

`AsyncInsert` should correctly bind named query parameters and it should return successfully. 

## Code example

Patch is attached that reproduces this behavior on `clickhouse-go`.
[0001-Add-test-for-named-parameters-with-async-insert.patch](https://github.com/user-attachments/files/16333697/0001-Add-test-for-named-parameters-with-async-insert.patch)

Example:

```go


	const tmpl = `CREATE TABLE test_async_insert ( col1 String, col2 DateTime64(9) ) ORDER BY tuple()`
	require.NoError(t, conn.Exec(ctx, tmpl))

	insertQueryWithoutParams := fmt.Sprintf(
		`INSERT INTO test_async_insert (col1, col2) VALUES ('%s', %d)`,
		"string",
		time.Now().UTC().UnixNano(),
	)
        // this will work
	require.NoError(t, conn.AsyncInsert(ctx, insertQueryWithoutParams, true))

        // this will not work
	const insertQuery = `INSERT INTO test_async_insert (col1, col2) VALUES ({c1:String}, {c2:DateTime64(9)})`
	chCtx := clickhouse.Context(ctx, clickhouse.WithParameters(clickhouse.Parameters{
		"c1": "1",
		"c2": strconv.FormatInt(time.Now().UnixNano(), 10),
	}))

```

## Error log

```log
        	Error:      	Received unexpected error:
        	            	code: 456, message: Substitution `c1` is not set: While executing WaitForAsyncInsert
        	Test:       	TestIssue199999
```

### Environment
* [x] `clickhouse-go` version: 543b1fbcbe4d980f8a6d05e1c18f5e98daad7f28
* [x] Interface: ClickHouse API 
* [x] Go version: Go 1.22
* [x] Operating system: Mac 14.5
* [x] ClickHouse version: 24.3.1.2672-alpine
* [ ] Is it a ClickHouse Cloud? Both self-managed or Cloud will show the same behavior
* [x] ClickHouse Server non-default settings, if any: none
* [x] `CREATE TABLE` statements for tables involved: Included in the patch
* [x] Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary: not required

**Comment by jkaflik** [comment] 2024-07-23 06:01
I can confirm it's reproducible. Possible that it's a missing compatibility in ClickHouse. The same was reported for ODBC driver: https://github.com/ClickHouse/clickhouse-odbc/issues/424

I will keep you updated when I have more details.

**Comment by jkaflik** [comment] 2024-07-25 12:32
ClickHouse issue for a reference: https://github.com/ClickHouse/ClickHouse/issues/67117

**Comment by jkaflik** [comment] 2024-08-23 05:31
Since it's not actionable on driver side, I will close this issue.

**Closed by jkaflik** 2024-08-23 05:31 UTC
Labels: bug
